#!/bin/bash

cat <<EOF

      ___          ___          ___   ___ 
     /\__\        /\__\        /\__\\ /\\__\\
    /  |  |      / /  /       / /  // /  /
   / | |  |     / /  /       / /  // /  / 
  / /| |  |__  / /  /  ___  / /  // /  /  
 / / | | /\__\\/ /__/  /\__\\/ /__// /__/   
 \/__| |/ /  /\ \  \ / /  /\ \  \\\ \  \   
     | / /  /  \ \  / /  /  \ \  \\\ \  \  
     |  /  /    \ \/ /  /    \ \  \\\ \  \ 
     / /  /      \  /  /      \ \__\\\ \__\\
     \/__/        \/__/        \/__/ \/__/
     
     
     - DOTFILES AND APPS FOR NULL -
       
       Alrighty, bucko.

       This scirpt will install 
       apps and dotfiles based on
       your OS.

EOF

echo $HOME

GREEN='\033[0;32m' 
YELLOW='\033[1;33m' 
NC='\033[0m'

linux_install () {
  echo -e "- ${GREEN}Installing Depenencies...${NC} -"
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
  sudo apt install python3 -y

  echo -e "- ${GREEN}Installing Awesome${NC} -"
  sudo apt install awesome -y
  echo -e "- ${GREEN}Installing Rofi${NC} -"
  sudo apt install rofi -y
  echo -e "- ${GREEN}Installing Nitrogen${NC} -"
  sudo apt install nitrogen -y 
  echo -e "- ${GREEN}Installing Compton${NC} -"
  sudo apt install compton -y 
  echo -e "- ${GREEN}Installing Alacritty${NC} -"
  git clone https://github.com/alacritty/alacritty.git alacritty-git
  cd alacritty-git

  rustup override set stable
  rustup update stable

  apt-get install cmake pkg-config libfreetype6-dev libfontconfig1-dev libxcb-xfixes0-dev libxkbcommon-dev 

  cargo build --release
  infocmp alacritty
  sudo tic -xe alacritty,alacritty-direct extra/alacritty.info

  sudo cp target/release/alacritty /usr/local/bin
  sudo cp extra/logo/alacritty-term.svg /usr/share/pixmaps/Alacritty.svg
  sudo desktop-file-install extra/linux/Alacritty.desktop
  sudo update-desktop-database

  sudo mkdir -p /usr/local/share/man/man1
  gzip -c extra/alacritty.man | sudo tee /usr/local/share/man/man1/alacritty.1.gz > /dev/null
  gzip -c extra/alacritty-msg.man | sudo tee /usr/local/share/man/man1/alacritty-msg.1.gz > /dev/null
  cd ../
  echo -e "- ${GREEN}Removing Alacritty Repo${NC} -"
  sudo rm -rf alacritty-git

  echo -e "- ${GREEN}Installing Pywal${NC} -"
  sudo pip3 install pywal
  echo -e "- ${GREEN}Installing Stow${NC} -"
  sudo apt install stow -y 
  echo -e "- ${GREEN}Installing Zsh${NC} -"
  sudo apt install zsh -y 
  echo -e "- ${GREEN}Installing Tmux${NC} -"
  sudo apt install tmux -y 
  echo -e "- ${GREEN}Installing Nvim${NC} -"
  sudo apt-get install neovim -y
  echo -e "- ${GREEN}Installing Brave${NC} -"
  sudo curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
  echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main"|sudo tee /etc/apt/sources.list.d/brave-browser-release.list
  sudo apt update
  sudo apt install brave-browser

  echo -e "- ${GREEN}Install complete!${NC} -"

  echo -e "- ${GREEN}Stowing files...${NC} -"

  echo -e "- ${GREEN}Stowing awesome${NC} -"
  stow awesome
  echo -e "- ${GREEN}Stowing rofi${NC} -"
  stow rofi 
  echo -e "- ${GREEN}Stowing alacritty${NC} -"
  stow alacritty 
  echo -e "- ${GREEN}Stowing zsh${NC} -"
  stow zsh 
  echo -e "- ${GREEN}Stowing tmux${NC} -"
  stow tmux 
  echo -e "- ${GREEN}Stowing nvim${NC} -"
  stow nvim 
}

max_install () {
  echo "bla"
}

linux_prompt () {
cat <<EOF

 		- APPS -
   * $(echo -e "${GREEN}AwesomeWM${NC}")
     - Window manager 
   * $(echo -e "${GREEN}Rofi${NC}")
     - Application launcher 
   * $(echo -e "${GREEN}Nitrogen${NC}")
     - Wallpaper engine 
   * $(echo -e "${GREEN}Compton${NC}")
     - Compositor 
   * $(echo -e "${GREEN}Alacritty${NC}")
     - Terminal 
   * $(echo -e "${GREEN}Pywal${NC}")
     - Color scheme based on wallpaper 
   * $(echo -e "${GREEN}Stow${NC}")
     - Used to place dotfiles in specific places
   * $(echo -e "${GREEN}Zsh${NC}")
     - Shell 
   * $(echo -e "${GREEN}Tmux${NC}")
     - Multiplexer 
   * $(echo -e "${GREEN}Nvim${NC}")
     - Editor 
   * $(echo -e "${GREEN}Brave${NC}")
     - Browser 

 		- DOTS -				- DEPENDENCIES -
   AWESOME:   $(echo -e "~/the_deets/${GREEN}awesome${NC}") 		$(echo -e "${YELLOW}Rust${NC}")
   ROFI:      $(echo -e "~/the_deets/${GREEN}rofi${NC}")			$(echo -e "${YELLOW}Python${NC}")
   ALACRITTY: $(echo -e "~/the_deets/${GREEN}alacritty${NC}")
   ZSH:       $(echo -e "~/the_deets/${GREEN}zsh${NC}")
   TMUX:      $(echo -e "~/the_deets/${GREEN}tmux${NC}")
   NVIM:      $(echo -e "~/the_deets/${GREEN}nvim${NC}")

EOF

read -p "Would you like to install the deets? (y)Yes/(n)No/(c)Cancel: " choice

case $choice in
[yY]* ) linux_install ;;
[nN]* ) echo "NO DEETS FOR YOU" ;;
[cC]* ) echo "DEETS CANCELED" ;;
*) echo "NO CHOICE CANCELING" exit ;;
esac
}

mac_prompt () {
	echo "bla"
}

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
	linux_prompt
elif [[ "$OSTYPE" == "darwin"* ]]; then
	mac_prompt
fi

