# COMPLETION
setopt globdots
autoload -U compinit
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit -u

bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'j' vi-down-line-or-history

# VI MODE
bindkey -v

# STYLE
(( ${+ZSH_HIGHLIGHT_STYLES} )) || typeset -A ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_STYLES[path]=none
ZSH_HIGHLIGHT_STYLES[path_prefix]=none

# PROMPT
PS1="%F{#b1bfa1}%1~%f %F{#e06f67}X%f "

# PLUGINS
source $HOME/.the_deets/zsh_config/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
